import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "next-themes";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "BraceFree",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <title>BraceFree - Invisible Aligners for a Confident Smile</title>
        <meta name="description" content="BraceFree offers invisible aligners for a confident smile. Straighten your teeth with expert care and advanced technology." />
        <meta name="keywords" content="invisible aligners, teeth straightening, dental care, smile, orthodontics, BraceFree" />
        <meta name="author" content="BraceFree" />
        <meta property="og:title" content="BraceFree - Invisible Aligners for a Confident Smile" />
        <meta property="og:description" content="BraceFree offers invisible aligners for a confident smile. Straighten your teeth with expert care and advanced technology." />
        <meta property="og:type" content="website" />
        <meta property="og:url" content="https://yourdomain.com/" />
        <meta property="og:image" content="https://yourdomain.com/images/og-image.jpg" />
        <meta name="twitter:card" content="summary_large_image" />
        <meta name="twitter:title" content="BraceFree - Invisible Aligners for a Confident Smile" />
        <meta name="twitter:description" content="BraceFree offers invisible aligners for a confident smile. Straighten your teeth with expert care and advanced technology." />
        <meta name="twitter:image" content="https://yourdomain.com/images/og-image.jpg" />
        <link rel="canonical" href="https://yourdomain.com/" />
        <meta name="robots" content="index, follow" />
      </head>
      <body className={`${roboto.variable} antialiased`}>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
